config/routes.rb
TechnologyBlog::Application.routes.draw do
  
  devise_for :users,:controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  
  get 'users/:user_id/blogs/import/new' => 'blogs#import_new' ,:as => 'import_new_user_blog'
  post 'users/:user_id/blogs/import' => 'blogs#import_create' ,:as => 'import_user_blog'
  get 'users/:user_id/blogs/export' => 'blogs#export',:as => "export_user_blog"
  
  resources :users,:only => ['index','destroy'] do
    resources :blogs 
  end
  
  root :to => "users#index"
  
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :title

  belongs_to :user
  has_many :blog_tags
  has_many :tags,:through => :blog_tags

  searchable do
    text :title, :boost => 5, :more_like_this => true
    text :content,:more_like_this => true
    date :updated_at
    integer :user_id

    text :tags,:more_like_this => true do
      self.tags.map(&:tag)
    end
  end

  def set_instans(hash)
    self.title = hash["title"]
    self.content = hash["content"]
    
    hash["tags"].each do |tag_s|
      tag = Tag.factory_tag(tag_s)
      self.tags << tag
    end

    self.created_at = DateTime.strptime(hash["created_at"],"%Y-%m-%d")
    self.updated_at = DateTime.strptime(hash["created_at"],"%Y-%m-%d")
  end

  def save_tags(tags_s)
    tags_s.convert_to_array.each do |tag_s|
      tag = Tag.factory_tag(tag_s)
      self.tags << tag
    end
  end
  
  def more_like_this
    results = Sunspot.more_like_this(self) do
      fields :content,:tags,:title
      minimum_document_frequency 30
    end
    return results.results
  end

  def self.full_text_search(user_id,search_word,page = 1)
    result = Blog.search do
      fulltext search_word
      with(:user_id, user_id)
      paginate :page => page, :per_page => Kaminari.config.config[:default_per_page]
      order_by :updated_at, :desc
    end
    @blogs = result.results
  end
  
  def to_hash
    blog_json = ActiveSupport::JSON.decode(self.to_json)
    tags = Array.new
    self.tags.each do |tag|
      tags << tag.tag
    end
    blog_json["tags"] = tags
     
    return blog_json
  end
end

app/controllers/blogs_controller.rb
require 'json'
require 'kconv'

class BlogsController < ApplicationController
  before_filter :find_user
  before_filter :set_iphone_format
  before_filter :find_tags,:only => [:new,:edit]
  layout :set_layout
  load_and_authorize_resource
  
  # GET /blogs
  # GET /blogs.json
  def index
    if search_word = (params[:search] || {})[:word]
      @blogs = Blog.full_text_search(@user.id,search_word,params[:page])
    elsif search_tag = (params[:search] || {})[:tag]
      @blogs = []
      @user.blogs.each do |blog|
        @blogs << blog if blog.tags.find(:first,:conditions => "tag = '#{search_tag}'")
      end
      @blogs = Kaminari.paginate_array(@blogs).page(params[:page])
    elsif search_date = (params[:search] || {})[:date]
      date = DateTime.strptime(search_date+"/1","%Y/%m/%d")
      @blogs = Blog.where{(created_at >= date) & (created_at < (date >> 1))}.page params[:page]
    else
      @blogs = @user.blogs.order("updated_at DESC").page params[:page]
    end
    @blogsize_calendar = create_blogs_size_every_month
    @tags_list = craete_tag_list
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs}
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    #@blog.more_like_this
    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = @user.blogs.build
    
    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = @user.blogs.build(params[:blog])
    @blog.save_tags(params[:tags][:tag])
    respond_to do |format|
      if @blog.save
        format.html { redirect_to user_blog_path(params[:user_id],@blog), notice: 'Blog was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog.tags.delete_all
    @blog.save_tags(params[:tags][:tag])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html{ redirect_to(user_blog_path(@user,@blog), :notice => 'Invoice was successfully updated.') }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to user_blogs_path(params[:user_id]) }
    end
  end

  def import_create
    json_array = JSON.parse(params[:file].read.kconv(Kconv::UTF8, Kconv::UTF8))

    Blog.record_timestamps = false
    json_array.each do |json_hash|
      blog = @user.blogs.build
      blog.set_instans(json_hash)
      blog.save
    end
    Blog.record_timestamps = true

    respond_to do |format|
      format.html { redirect_to user_blogs_path(@user)}
    end
  end

  def import_new
    respond_to do |format|
      format.html
    end
  end
  
  def export
    blogs = @user.blogs
    
    blogs_json = Array.new
    blogs.each do |blog|
      blogs_json << blog.to_hash
    end
    
    respond_to do |format|
      format.json {render json: blogs_json}
    end
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end
  
  def find_tags
    @tags = Tag.all
  end
  
  def set_iphone_format
    if iphone_request? && request.format == "text/html"
      request.format = :iphone
    end
  end
  
  def set_layout
    iphone_request? ? "iphone" : "application"
  end
  
  def iphone_request?
    request.user_agent =~ /(Mobile.+Safari)/
  end
  
  def current_ability
    if current_user
      if current_user.id == @user.id
        def current_user.admin?
          true
        end
      end
    end
    @current_ability ||= Ability.new(current_user)
  end
  
  #return hash[year][month] = blogs.size
  def create_blogs_size_every_month
    calender = Hash.new
    
    first_blog = @user.blogs.order("created_at ASC").first
    if !first_blog
      return calender
    end
    
    (first_blog.created_at.year..Date.today.year).each do |year|
      calender[year] = Hash.new
      (1..12).each do |month|
        date = Date::new(year,month,1)
        calender[year][month] = @user.blogs.where{(created_at >= date) & (created_at < date >> 1)}.size
      end
    end
    
    return calender
  end
  
  #return hash[tag.tag] = tag_count
  def craete_tag_list
    tags_list = Hash.new
    @user.blogs.each do |blog| 
      blog.tags.each do |tag|
        if tags_list.key?(tag.tag)
          tags_list[tag.tag] += 1
        else
          tags_list[tag.tag] = 1
        end
      end 
    end

    sort_tags_list = Hash.new
    tags_list.sort_by{|key,val| -val}.each do |tag|
      sort_tags_list[tag.first] = tag.second
    end

    return sort_tags_list
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def date_to_s(date)
    date.strftime("%Y-%m-%d")
  end

  def tags_to_s(tags)
    tags_s = ""
    tags.each do |tag|
      tags_s += tag.tag + ","
    end
    tags_s[0..-2]
  end
end

app/views/blogs/_calendar.html.erb
<article class="calendar">
	<h2>月刊アーカイブ</h2>
	<% calendar.each_key do |year| %>
	<div class="year">
		<% calendar[year].each_key do |month| %>
		<div class="month">
			<% if calendar[year][month] != 0%>
			<%= link_to  year.to_s+"/"+month.to_s+"  ("+calendar[year][month].to_s+")",{:controller => "blogs", :action => "index", :search=>{:date=>year.to_s+"/"+month.to_s}} %>
			<% end %>
		</div>
		<% end %>
	</div>
	<% end %>
</article>

app/views/blogs/_form.html.erb
<%= form_for [@user,@blog] do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content,:size=>"140x20"%>
  </div>

  <div class="field">
  	<%= text_field :tags,:tag,:value => tags_to_s(@blog.tags),:autocomplete => "off" %>
	<div id="suggest" style="display:none;"></div>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
function startSuggest() {
	array = new Array();
	<% @tags.each do |tag| %>
		array.push("<%= tag.tag %>");
	<% end %>
  new Suggest.LocalMulti(
        "tags_tag",    // 入力のエレメントID
        "suggest", // 補完候補を表示するエリアのID
        array,      // 補完候補の検索対象となる配列
        {dispMax: 10, prefix: true}); // オプション
}

window.addEventListener ?
  window.addEventListener('load', startSuggest, false) :
  window.attachEvent('onload', startSuggest);
</script>

app/views/blogs/_tagslist.html.erb
<article class="tagslist">
	<h2>タグの一覧</h2>
	<ul class="tags">
		<% tags_list.each_key do |key| %>

		<li class="tag">
			<%= link_to key, {:controller => "blogs", :action => "index", :search=>{:tag=>key}} %>
			<%= " x "+tags_list[key].to_s %>
		</li>
		<% end %>
	</ul>
</article>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', user_blog_path(params[:user_id],@blog) %> |

app/views/blogs/import_new.html.erb
<%= form_tag(import_user_blog_path(@user), {:multipart => true})  do %>

  <%= label_tag 'JSON取り込み' %><br />
  <%= file_field_tag "file" %><br />
  
  <%= submit_tag "submit" %>

<% end %> 

app/views/blogs/index.html.erb
<header>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<ul class="nav pull-right">
				<li>
					<% if can? :create,Blog %>
					<%= link_to 'New Blog', new_user_blog_path(params[:user_id]) %>
					<% end %>
				</li>
				<li>
					<% if can? :create,Blog %>
					<%= link_to("import",import_new_user_blog_path(@user)) %>
					<% end %>
				</li>
			</ul>
		</div>
	</div>
</header>

<br/>
<br/>
<br/>

<%= form_tag(user_blogs_path(@user),{:method => :get}) do %>
<%= search_field(:search,:word) %>
<%= submit_tag '検索' %>
<% end %>

<div id="main">
	<%= breadcrumb %>
	<section class="autopagerize_page_element" id="blogs">
		<% @blogs.each do |blog| %>
		<article class="blog" itemscope="itemscope" itemtype="http://schema.org/Article">
			<h2><%= link_to blog.title,[@user,blog] %> </h2>
			<div class="body">
				<%= CGI.escapeHTML(remove_markdown(blog.content)) %><%# マークダウン記法の中のHTMLがエスケープされてなかったので %>
			</div>

			<div class="date" id="created_at">
				<%= "created_at : " + date_to_s(blog.created_at) %>
			</div>
			<div class="date" id="updated_at">
				<%= "updated_at : " + date_to_s(blog.updated_at) %>
			</div>
			<% if can? :edit,blog %>
			<%= link_to 'Edit', edit_user_blog_path(params[:user_id],blog) %>
			<% end %>
			<% if can? :delete,blog %>
			<%= link_to 'Destroy', user_blog_path(params[:user_id],blog), method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</article>
		<% end %>

		<br />
		<%= paginate @blogs %>
	</section>

	<aside id="sidebar">
		<%= render 'calendar',:calendar => @blogsize_calendar %>
		<%= render 'tagslist',:tags_list => @tags_list %>
	</aside>
</div>

app/views/blogs/index.iphone.erb
<div data-role="page" id="blogs">
	<div data-role="content">
		<select>
			<option>日付を指定して検索</option>
			<% @blogsize_calendar.each_key do |year| %>
			<% @blogsize_calendar[year].each_key do |month| %>
			<% if @blogsize_calendar[year][month] != 0 %>
			<option value="<%= "blogs?search[date]=" + year.to_s+"/"+month.to_s %>"><%= year.to_s+"/"+month.to_s %></option>
			<% end %>
			<% end %>
			<% end %>
		</select>

		<select>
			<option>タグを指定して検索</option>
			<% @tags_list.each_key do |key| %>
			<option value="<%= "blogs?search[tag]=" + key %>"><%= key %></option>
			<% end %>
		</select>
		
		<ul id="items" data-role="listview" data-inset="true" data-theme="c">
		</ul>
	</div>
</div>

<%= javascript_include_tag "mobile/blog/index.js" %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

app/views/blogs/show.html.erb
<%= breadcrumb %>

<%= tweet_button({:text => @blog.title,:via => nil,:count => "horizontal"}) %>

<article id="blog" itemscope="itemscope" itemtype="http://schema.org/Article">
	<h1 class="title" itemprop="name"> <%= @blog.title %> </h1>
	<div class="row">
		<div class="body" itemprop="articleBody">
			<%= markdown @blog.content %>
		</div>
	</div>

	<ul class="tags inline">
		<% @blog.tags.each do |tag| %>
		<li>
			<%= link_to tag.tag, {:controller => "blogs", :action => "index", :search=>{:tag=>tag.tag}} %>
		</li>
		<% end %>
	</ul>
</article>

app/views/blogs/show.iphone.erb
<div data-role="page" id="blogs">
	<%= tweet_button({:text => @blog.title,:via => nil,:count => "horizontal"}) %>
	<div data-role="content">
		<h1 class="title" itemprop="name"> <%= @blog.title %> </h1>
		<div class="row">
			<div class="body" itemprop="articleBody">
				<p><%= markdown @blog.content %></p>
			</div>
		</div>

		<ul data-role="listview">
			<% @blog.tags.each do |tag| %>
			<li>
				<%= link_to tag.tag, {:controller => "blogs", :action => "index", :search=>{:tag=>tag.tag}} %>
			</li>
			<% end %>
		</ul>
	</div>
</div>