config/routes.rb
TechnologyBlog::Application.routes.draw do
  
  devise_for :users,:controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  
  get 'users/:user_id/blogs/import/new' => 'blogs#import_new' ,:as => 'import_new_user_blog'
  post 'users/:user_id/blogs/import' => 'blogs#import_create' ,:as => 'import_user_blog'
  get 'users/:user_id/blogs/export' => 'blogs#export',:as => "export_user_blog"
  
  resources :users,:only => ['index','destroy'] do
    resources :blogs 
  end
  
  root :to => "users#index"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :fb_user_id, :name
  
  has_many :blogs

  def self.find_or_create_from_auth_hash(auth_hash)
    user_data = auth_hash.extra.raw_info
    if user = User.where(:fb_user_id => user_data.id).first
      user
    else # Create a user with a stub password. 
      User.create!(:fb_user_id => user_data.id, :name => user_data.name, :email => user_data.email)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    
    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.blogs.destroy_all
    @user.destroy
    
    respond_to do |format|
      format.html { redirect_to root_path }
    end
  end
  
  def current_ability
    if current_user
      if @user == current_user
        def current_user.admin?
          true
        end
      end
    end
    
    @current_ability ||= Ability.new(current_user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Listing users</h1>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<% if user_signed_in? %>
  Sign in as <strong><%= current_user.name %></strong>
  |
  <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
  <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>
<br/>

<% if user_signed_in? %>
	<%= link_to 'アカウント削除', user_path(current_user), method: :delete  %><br/>
<% end%>

<table>
  <tr>
  </tr>

  <% @users.each do |user| %>
  	<tr>
  	  <%= user.name %>
  	</tr>
    <tr>
    	<%= link_to "ユーザが投稿したブログ",user_blogs_path(user) %>
    </tr>
    <br/>
  <% end %>
</table>

<br />